# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/QbotMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QbotGUI(object):
    def setupUi(self, QbotGUI):
        QbotGUI.setObjectName("QbotGUI")
        QbotGUI.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(QbotGUI)
        self.centralwidget.setObjectName("centralwidget")
        QbotGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QbotGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        QbotGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QbotGUI)
        self.statusbar.setObjectName("statusbar")
        QbotGUI.setStatusBar(self.statusbar)
        self.Menu1 = QtWidgets.QAction(QbotGUI)
        self.Menu1.setObjectName("Menu1")
        self.menuTest.addAction(self.Menu1)
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(QbotGUI)
        QtCore.QMetaObject.connectSlotsByName(QbotGUI)

    def retranslateUi(self, QbotGUI):
        _translate = QtCore.QCoreApplication.translate
        QbotGUI.setWindowTitle(_translate("QbotGUI", "QbotGUI"))
        self.menuTest.setTitle(_translate("QbotGUI", "Test"))
        self.Menu1.setText(_translate("QbotGUI", "Menu1"))
